---
name: junos_change_ospf
run-name: ${{ github.actor }} is exec junos_change_ospf
on: 
  push:
    paths:
      - 'device/VMX01/*'
      - 'device/VMX02/*'

jobs:
  ansible_in_docker:
    runs-on: ubuntu-latest
    # needs: approval
    container:
      image: kaiuchida/ansible-execution-env:1.0
      options: --user root
    steps:
      - name: check my ip
        run: curl http://inet-ip.info/

      - name: checkout code
        uses: actions/checkout@v3

      - name: connectivity_check
        uses: corrupt952/retry-command@v1.0.7
        with:
          command: ansible-playbook -i inventory junos_change_ospf.yml --tags "connectivity_check"
          max_attempts: 5
          retry_interval: 5
      
      - name: run junos_change_ospf.yml
        run: ansible-playbook -i inventory junos_change_ospf.yml
