name: check ip
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: workflow_dispatch
jobs:
  ansible_in_docker:
    runs-on: ubuntu-latest
    steps:
      # - name: checkout code
      #   uses: actions/checkout@v3
      
      - name: ping01
        run: curl 35.77.195.143:37682

      - name: ping02
        run: curl 35.77.195.143:37682
