name: GitHub Ansible Test
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch]
jobs:
  check_my_ip:
    runs-on: ubuntu-latest
    steps:
      - name: check my ip
        run: curl http://inet-ip.info/

  # approval:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: test
  #   steps:
  #     - run: echo "waiting approval"

  ansible_in_docker:
    runs-on: ubuntu-latest
    # needs: approval
    container: kaiuchida/ansible-execution-env:1.0
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: cat file
        run: cat test.yml

      - name: ansible test
        run: ansible-playbook test.yml
