name: GitHub Ansible Test
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch]
jobs:
  check_my_ip:
    runs-on: ubuntu-latest
    steps:
      - name: check my ip
        run: curl http://inet-ip.info/

  approval:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - run: echo "waiting approval"

  ansible_in_docker:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: cat file
        run: cat test.yml

      - name: curl
        run: curl 66.129.234.214:38001

      - name: docker pull
        run: docker pull kaiuchida/ansible-execution-env:1.0

      - name: docker images
        run: docker images

      - name: docker run
        run: |
          docker run --name ansible_container -d  -v $(pwd):/runner kaiuchida/ansible-execution-env:1.0 sleep infinity

      - name: docker exec curl
        run: |
          docker exec ansible_container curl 66.129.234.214:38001

      - name: docker exec ansible
        run: |
          docker exec ansible_container ansible-playbook -i inventory junos_test.yml
