name: GitHub Ansible Test
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch, push]
jobs:
  ansible_in_docker:
    runs-on: ubuntu-latest
    # container: quay.io/ansible/ansible-runner:stable-2.12-devel
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: cat file
        run: cat test.yml

      - name: docker pull
        run: docker pull quay.io/ansible/ansible-runner:stable-2.12-devel

      - name: docker images
        run: docker images

      - name: docker run
        run: |
          docker run --rm -v $(pwd):/runner quay.io/ansible/ansible-runner:stable-2.12-devel ansible-playbook test.yml
