name: GitHub Ansible Test
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [workflow_dispatch, push]
jobs:
  ansible_in_docker:
    runs-on: ubuntu-latest
    # container: quay.io/ansible/ansible-runner:stable-2.12-devel
    steps:
      # - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: cat file
        run: cat test.yml

      - name: docker pull
        run: docker pull quay.io/ansible/ansible-runner:stable-2.12-devel

      - name: docker images
        run: docker images

      - name: docker run
        run: |
          docker run --rm -d --name runner -v .:/runner quay.io/ansible/ansible-runner:stable-2.12-devel sleep infinity

      - name: docker ps
        run: docker ps

      - name: docker exec ls
        run: docker exec runner ls

      - name: docker exec ls
        run: docker exec runner cat test.yml

      - name: docker exec
        run: docker exec runner ansible-playbook test.yml
